name: Release

on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Version bump type"
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
      open_pr:
        description: "Request consumers to open PRs"
        required: false
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  release:
    uses: dsanroman96/workflow-templates/.github/workflows/dependency-release.yml@main
    with:
      bump: ${{ inputs.bump }}
      project_type: typescript
      open_pr: ${{ inputs.open_pr }}
    secrets: inherit
